apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    # labels allows services to search PODs.
    name: voting-service
    app: demo-voting-app
spec:
  type: LoadBalancer
  # load Balancer service can be accessed from the outside world.
  # default type is clusterIP
  # service created with clusterIP is available only in the cluster.
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: voting-app-pod
    app: demo-voting-app

